// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwkxmlzyrxlcgwfeiewb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3a3htbHp5cnhsY2d3ZmVpZXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTc0NzEsImV4cCI6MjA3MDQzMzQ3MX0.2XAaBio-Jvs7B8HwVYMFpUuSZ-n8sLiXgS5tuPCNFXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});